#
# Module manifest for module 'AADExporter'
# Generated by: Laurie Rhodes
# Created: 2025-08-31
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'AADExporter.psm1'

# Version number of this module.
ModuleVersion = '3.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '4a8b9c2d-1e3f-4567-89ab-cdef01234567'

# Author of this module
Author = 'Laurie Rhodes'

# Company or vendor of this module
CompanyName = 'Enterprise'

# Copyright statement for this module
Copyright = 'Laurie Rhodes under MIT License'

# Description of the functionality provided by this module
Description = 'Azure Active Directory data export module for Azure Data Explorer integration via Event Hub'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # Core orchestration
    'Invoke-AADDataExport',
    
    # Data export modules
    'Export-AADUsers',
    'Export-AADGroups', 
    'Export-AADGroupMemberships',
    
    # Authentication
    'Get-AzureADToken',
    
    # Event Hub integration
    'Send-EventsToEventHub',
    
    # Error handling and resilience
    'Invoke-WithRetry',
    'Invoke-GraphAPIWithRetry',
    'Get-ErrorType',
    'Test-ShouldRetry',
    'Get-HttpStatusCode',
    
    # Telemetry and monitoring
    'Write-CustomTelemetry',
    'Write-DependencyTelemetry',
    'Write-ExportProgress',
    'New-CorrelationContext',
    
    # Storage utilities
    'Get-AzTableStorageData',
    'Set-AzTableStorageData',
    'Get-Events',
    'Get-StorageTableValue',
    'Push-StorageTableValue'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Azure', 'AzureAD', 'GraphAPI', 'EventHub', 'DataExport', 'ADX', 'Identity', 'Telemetry', 'Enterprise')

        # ReleaseNotes of this module
        ReleaseNotes = @'
Version 3.0 - Comprehensive Refactoring and Cleanup:
- BREAKING: Renamed module from AZRest to AADExporter
- IMPROVED: Eliminated nested catch blocks throughout codebase
- ENHANCED: Streamlined error handling with consistent patterns
- OPTIMIZED: Cleaned up function architecture and dependencies
- STANDARDIZED: Consistent code formatting and documentation
- PRODUCTION-READY: Enterprise-grade error handling and logging
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}